### PR TITLE
feat: Updated to preview 9

### PR DESCRIPTION
**Pull request by pivendren**
Updated to preview 9. 
Changes made based on announcement blog: https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-9/

### CODE REVIEW

**Comment by zbecknell** [comment]
When attempting to use server mode, this is stuck at "Loading...".

**Comment by Suchiman** [comment]
Yeah this is happening because it appears that preview 9 now requires a razor page to be used for kicking off server side blazor.

**Comment by acotterell1973** [comment]
should have looked at this first... ran into the same problem.

**Comment by acotterell1973** [comment]
@zbecknell ... where you able to figure this out?

**Comment by Suchiman** [comment]
I have an idea (and some time about now), will figure this out

**Pull request merged**
